apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarotmate-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tarotmate-backend
  template:
    metadata:
      labels:
        app: tarotmate-backend
    spec:
      containers:
      - name: tarotmate-backend
        image: bufstudio/tarotmate-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: database-url
        - name: AWS_COGNITO_USER_POOL_ID
          valueFrom:
            secretKeyRef:
              name: aws-cognito-secrets
              key: user-pool-id
        - name: AWS_COGNITO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: aws-cognito-secrets
              key: client-id